services:
  server:
    build: .
    ports:
      - "48100:48100"
      - "48102:48102"
    volumes:
      - ./certs:/certs:ro
    command:
      - --role
      - server
      - --protocol
      - tls
      - --listen
      - 0.0.0.0:48100
      - --admin-listen
      - 0.0.0.0:48102
      - --cert
      - /certs/cert.pem
      - --key
      - /certs/key.pem
      - --tunnel-port-range
      - 8000-9000

  client:
    build: .
    depends_on:
      - server
    volumes:
      - ./certs:/certs:ro
    command:
      - --role
      - client
      - --remote
      - tls://server:48100
      - --cert
      - /certs/cert.pem
      - --tls-host
      - localhost
      - --listen
      - 0.0.0.0:48101
