use base64::{engine::general_purpose::STANDARD, Engine};
use std::collections::HashSet;

/// AutoProxy 规则列表解析器
#[derive(Default)]
pub struct AutoProxyList {
    /// 白名单域名 (@@||domain)
    pub whitelist_domains: HashSet<String>,
    /// 需要代理的域名 (||domain)
    pub proxy_domains: HashSet<String>,
    /// 关键词规则
    pub keywords: Vec<String>,
    /// URL前缀规则 (|http...)
    pub url_prefixes: Vec<String>,
    /// 正则表达式规则 (/regexp/)
    pub regexps: Vec<String>,
}

impl AutoProxyList {
    pub fn parse(base64_content: &str) -> anyhow::Result<Self> {
        let decoded = STANDARD.decode(base64_content.trim())?;
        let content = String::from_utf8(decoded)?;
        let mut result = AutoProxyList::default();

        for line in content.lines() {
            let line = line.trim();

            // Skip empty lines, comments, and header
            if line.is_empty()
                || line.starts_with('!')
                || line.starts_with('[')
                || line.starts_with('#')
            {
                continue;
            }

            // 白名单域名: @@||domain
            if let Some(domain) = line.strip_prefix("@@||") {
                let domain = Self::clean_domain(domain);
                if !domain.is_empty() {
                    result.whitelist_domains.insert(domain);
                }
            }
            // 域名规则: ||domain
            else if let Some(domain) = line.strip_prefix("||") {
                let domain = Self::clean_domain(domain);
                if !domain.is_empty() {
                    result.proxy_domains.insert(domain);
                }
            }
            // URL前缀: |http...
            else if let Some(prefix) = line.strip_prefix('|') {
                if prefix.starts_with("http") {
                    result.url_prefixes.push(prefix.to_string());
                }
            }
            // 正则表达式: /regexp/
            else if line.starts_with('/') && line.ends_with('/') && line.len() > 2 {
                let regex = &line[1..line.len() - 1];
                result.regexps.push(regex.to_string());
            }
            // 域名后缀: .domain.com
            else if let Some(suffix) = line.strip_prefix('.') {
                let domain = Self::clean_domain(suffix);
                if !domain.is_empty() {
                    result.proxy_domains.insert(domain);
                }
            }
            // 普通关键词
            else if !line.contains('*') && !line.contains('^') {
                // 简单关键词，不含通配符
                result.keywords.push(line.to_string());
            }
        }

        tracing::info!(
            "AutoProxyList parsed: {} whitelist domains, {} proxy domains, {} keywords, {} url prefixes, {} regexps",
            result.whitelist_domains.len(),
            result.proxy_domains.len(),
            result.keywords.len(),
            result.url_prefixes.len(),
            result.regexps.len()
        );

        Ok(result)
    }

    /// 清理域名，移除路径和端口
    fn clean_domain(s: &str) -> String {
        s.split(|c| c == '/' || c == '^' || c == ':' || c == '?')
            .next()
            .unwrap_or("")
            .to_lowercase()
    }

    /// 生成 PAC 文件内容
    pub fn generate_pac(&self, proxy: &str) -> String {
        let mut pac = String::with_capacity(64 * 1024);

        // PAC 头部
        pac.push_str("// Auto-generated PAC file from AutoProxy list\n");
        pac.push_str("// Generated by rsnova\n\n");

        // 代理配置
        pac.push_str(&format!("var proxy = \"{}\";\n\n", proxy));

        // 白名单域名
        pac.push_str("var whitelist = {\n");
        for domain in &self.whitelist_domains {
            pac.push_str(&format!("  \"{}\": 1,\n", domain));
        }
        pac.push_str("};\n\n");

        // 代理域名
        pac.push_str("var domains = {\n");
        for domain in &self.proxy_domains {
            pac.push_str(&format!("  \"{}\": 1,\n", domain));
        }
        pac.push_str("};\n\n");

        // 关键词
        pac.push_str("var keywords = [\n");
        for keyword in &self.keywords {
            let escaped = keyword.replace('\\', "\\\\").replace('"', "\\\"");
            pac.push_str(&format!("  \"{}\",\n", escaped));
        }
        pac.push_str("];\n\n");

        // URL前缀
        pac.push_str("var urlPrefixes = [\n");
        for prefix in &self.url_prefixes {
            let escaped = prefix.replace('\\', "\\\\").replace('"', "\\\"");
            pac.push_str(&format!("  \"{}\",\n", escaped));
        }
        pac.push_str("];\n\n");

        // 正则表达式
        pac.push_str("var regexps = [\n");
        for regex in &self.regexps {
            // 转义正则中的特殊字符用于 JS
            let escaped = regex.replace('\\', "\\\\");
            pac.push_str(&format!("  /{}/i,\n", escaped));
        }
        pac.push_str("];\n\n");

        // FindProxyForURL 函数
        pac.push_str(
            r#"function FindProxyForURL(url, host) {
    // 域名匹配：检查域名及所有父域名
    function matchDomain(h, dict) {
        while (h) {
            if (dict.hasOwnProperty(h)) return true;
            var idx = h.indexOf('.');
            if (idx < 0) break;
            h = h.slice(idx + 1);
        }
        return false;
    }

    host = host.toLowerCase();
    url = url.toLowerCase();

    // 1. 白名单优先，直连
    if (matchDomain(host, whitelist)) {
        return "DIRECT";
    }

    // 2. 域名规则
    if (matchDomain(host, domains)) {
        return proxy;
    }

    // 3. 关键词匹配
    for (var i = 0; i < keywords.length; i++) {
        if (url.indexOf(keywords[i]) >= 0) {
            return proxy;
        }
    }

    // 4. URL前缀匹配
    for (var i = 0; i < urlPrefixes.length; i++) {
        if (url.indexOf(urlPrefixes[i]) === 0) {
            return proxy;
        }
    }

    // 5. 正则匹配
    for (var i = 0; i < regexps.length; i++) {
        if (regexps[i].test(url)) {
            return proxy;
        }
    }

    // 默认直连
    return "DIRECT";
}
"#,
        );

        pac
    }
}

/// 从 URL 下载 AutoProxy 列表并生成 PAC
pub async fn fetch_and_generate_pac(
    autoproxy_url: &str,
    proxy: &str,
    fetch_proxy: Option<&str>,
) -> anyhow::Result<Vec<u8>> {
    tracing::info!(
        "Fetching autoproxy list from {} via {:?}",
        autoproxy_url,
        fetch_proxy
    );

    let mut builder = reqwest::Client::builder().timeout(std::time::Duration::from_secs(30));

    if let Some(proxy_url) = fetch_proxy {
        let proxy = reqwest::Proxy::all(proxy_url)?;
        builder = builder.proxy(proxy);
    }

    let client = builder.build()?;
    let response = client.get(autoproxy_url).send().await?;
    let base64_content = response.text().await?;

    let autoproxy_list = AutoProxyList::parse(&base64_content)?;
    let pac = autoproxy_list.generate_pac(proxy);

    Ok(pac.into_bytes())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_rules() {
        // 模拟 base64 编码的 autoproxy 内容
        let content = r#"[AutoProxy 0.2.9]
! comment line
||google.com
||youtube.com
@@||direct.cn
|https://blocked.site
.facebook.com
keyword
/regexp/"#;
        let base64_content = STANDARD.encode(content);

        let autoproxy_list = AutoProxyList::parse(&base64_content).unwrap();

        assert!(autoproxy_list.proxy_domains.contains("google.com"));
        assert!(autoproxy_list.proxy_domains.contains("youtube.com"));
        assert!(autoproxy_list.proxy_domains.contains("facebook.com"));
        assert!(autoproxy_list.whitelist_domains.contains("direct.cn"));
        assert!(autoproxy_list.url_prefixes.contains(&"https://blocked.site".to_string()));
        assert!(autoproxy_list.keywords.contains(&"keyword".to_string()));
        assert!(autoproxy_list.regexps.contains(&"regexp".to_string()));
    }
}
