name: Build Releases
on:
  push:
    tags:
      - v*
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release Tag'
        required: true
        type: string

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build-cross:
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: full
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-unknown-linux-musl
          - arm-unknown-linux-musleabi
          - arm-unknown-linux-musleabihf

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        run: |
          rustup set profile minimal
          rustup toolchain install stable
          rustup default stable
          rustup override set stable
          rustup target add --toolchain stable ${{ matrix.target }}

      - name: Install cross
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Build ${{ matrix.target }}
        timeout-minutes: 120
        run: |
          chmod +x ./ci/build_linux.sh
          ./ci/build_linux.sh ${{ matrix.target }}

      - name: Upload Github Assets
        uses: softprops/action-gh-release@v2
        with:
          files: ci/release/*
          prerelease: ${{ contains(github.ref_name, '-') }}
          tag_name: ${{ inputs.tag || github.ref_name }}

  build-macos-x86:
    runs-on: macos-latest
    env:
      RUST_BACKTRACE: full
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        run: |
          rustup set profile minimal
          rustup toolchain install stable
          rustup default stable
          rustup override set stable
          rustup target add --toolchain stable x86_64-apple-darwin

      - name: Build release
        shell: bash
        run: |
          chmod +x ./ci/build_other.sh
          ./ci/build_other.sh x86_64-apple-darwin

      - name: Upload Github Assets
        uses: softprops/action-gh-release@v2
        with:
          files: ci/release/*
          prerelease: ${{ contains(github.ref_name, '-') }}
          tag_name: ${{ inputs.tag || github.ref_name }}

  build-macos-arm:
    runs-on: macos-latest
    env:
      RUST_BACKTRACE: full
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        run: |
          rustup set profile minimal
          rustup toolchain install stable
          rustup default stable
          rustup override set stable
          rustup target add --toolchain stable aarch64-apple-darwin

      - name: Build release
        shell: bash
        run: |
          chmod +x ./ci/build_other.sh
          ./ci/build_other.sh aarch64-apple-darwin

      - name: Upload Github Assets
        uses: softprops/action-gh-release@v2
        with:
          files: ci/release/*
          prerelease: ${{ contains(github.ref_name, '-') }}
          tag_name: ${{ inputs.tag || github.ref_name }}

  build-windows:
    runs-on: windows-latest
    env:
      RUSTFLAGS: "-C target-feature=+crt-static"
      RUST_BACKTRACE: full
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        run: |
          rustup set profile minimal
          rustup toolchain install stable
          rustup default stable
          rustup override set stable

      - name: Build release
        shell: bash
        run: |
          chmod +x ./ci/build_other.sh
          ./ci/build_other.sh x86_64-pc-windows-msvc

      - name: Upload Github Assets
        uses: softprops/action-gh-release@v2
        with:
          files: ci/release/*
          prerelease: ${{ contains(github.ref_name, '-') }}
          tag_name: ${{ inputs.tag || github.ref_name }}
